### ISSUE TITLE
relative pathways in run scripts

### ISSUE THREAD

**Issue by ChristyPeterson** [mikeyweigand/Pertussis_n257#1]
I'm not sure if this is necessarily an issue, but thought I'd let you know that your scripts contain specific pathways that need to be changed for others attempting to use them.

Some I've found so far:
pairwise-mauve-all.pl line 85 - specific path to your location of the pairwise-mauve-parallel.sh file
pairwise-mauve-parallel.sh line 54 - specific path to progressiveMauve tool

Feel free to close the issue after, but thought for others trying to run the scripts it would be good to know that you will need to change these lines to get them working.

**Comment by ChristyPeterson** [comment]
You also can't use hyphens in your genome names as that seriously messes with the second set of scripts (backbone-clean and collinear-check).

**Comment by mikeyweigand** [comment]
@ChristyPeterson This is just simple laziness. I'll clean these up. Thanks.

**Comment by mikeyweigand** [comment]
These and a few other bugs should be resolved. I also added some notes to the bottom of the workflow description to warn about filename parsing errors due to '-' characters.

**Comment by ChristyPeterson** [comment]
Thanks for making these scripts available @mikeyweigand, they've been seriously beneficial for my pertussis WGS analysis!

**Comment by mikeyweigand** [comment]
@ChristyPeterson glad to hear. We're continuing to do a lot of pertussis genomic analyses. If you're interested to learn more or have questions feel free to communicate directly -- mweigand at cdc dot gov.
