### ISSUE TITLE
backbone2matrix.pl compilation errors

### ISSUE THREAD

**Issue by ChristyPeterson** [mikeyweigand/Pertussis_n257#2]
Received this error when running the backbone2matrix.pl script:
```Experimental keys on scalar is now forbidden at mauve.backbone2matrix.pl line 84.
Type of arg 1 to keys must be hash or array (not hash element) at mauve.backbone2matrix.pl line 84, near "})"
Execution of mauve.backbone2matrix.pl aborted due to compilation errors.
```

I'm running Perl 5.26.2, and changed line 84 to the following to get the script to run:
`foreach my$cc (sort{$a <=> $b}keys%{$ghash{$g2}}){`
original was this:
`foreach my$cc (sort{$a <=> $b}keys$ghash{$g2}){`

**Comment by mikeyweigand** [comment]
I had not encountered this error with perl 5.18.2. The line has been edited as you suggest and I don't (yet) see any collateral damage. The original is still there behind a comment just in case. Thanks!

**Comment by ChristyPeterson** [comment]
Thought I'd mention that I had looked around on stackoverflow and it seems like its something that was changed post 5.18, I think earlier versions of perl should work with the original version
