### ISSUE TITLE
ISmatrix.add-strain-spec.pl

### ISSUE THREAD

**Issue by alexandergz1983** [mikeyweigand/Pertussis_n257#4]
Dear Michael  Weigand.

In advance, congratulate you on this great job.
I have a question about script ISmatrix.add-strain-spec.pl, how did you choose this sequence 'aattcgcataatgtatattatgtaaagt' or what was the protocol for your choice?
Thanks.

**Comment by mikeyweigand** [comment]
Hi Alexander. That is the dif sequence for Bordetella. It's not used in 'ISmatrix.add-strain-spec.pl' but rather in scripts for calculating inversion balance in [Bordetella_species](https://github.com/mikeyweigand/Bordetella_species). The sequence was determined from [Kono 2011](https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-12-19). See [Weigand 2019 ](https://msystems.asm.org/content/4/6/e00702-19) for details.

**Comment by alexandergz1983** [comment]
Thanks.
