### ISSUE TITLE
Convert IS matrices to rbm format.

### ISSUE THREAD

**Issue by alexandergz1983** [mikeyweigand/Pertussis_n257#5]
Dear Michael

I write to you again for the following, in the analysis protocol reference is made to the following script: "ISmatrix2rbm.pl" for Convert IS matrices to rbm format. However, this script doesn't seem to be available or am I wrong, and is it part of another script? ...

Sorry for the inconvenience and thank you very much.

Regards.

**Comment by mikeyweigand** [comment]
@alexandergz1983 sorry, it was missing. It's been added now. Thanks for letting me know.
